document.write('<code>window.innerHeight</code> 窗口高度: ' + window.innerHeight + '<br />')
document.write('<code>window.innerWidth</code> 窗口宽度:' + window.innerWidth  + '<br />')
document.write('<code></code>' + window.pageXOffset + '<br />')
document.write('<code></code>' + window.pageYOffset + '<br />')
document.write('<code>window.screenX</code> 文档滚动的水平距离: ' + window.screenX + '<br />')
document.write('<code>window.screenY</code> 文档滚动的垂直距离: ' + window.screenY + '<br />')
document.write('<code>window.location</code> : ' + window.location + '<br />')
document.write('<code>window.document</code> : ' + window.document + '<br />')
document.write('<code>window.history</code> : ' + window.history + '<br />')
document.write('<code>window.history.length</code> : ' + window.history.length + '<br />')
document.write('<code>window.screen</code> : ' + window.screen + '<br />')
document.write('<code>window.screen.width</code> : ' + window.screen.width + '<br />')
document.write('<code>window.screen.height</code> : ' + window.screen.height + '<br />')
// 
// alert('This is .alert')
// print()
// open('https://cn.bing.com/?mkt=zh-CN&ensearch=1&FORM=BEHPTB')